name: Daily Update Full Database Dump

on:
  # Trigger update at UTC+0 23:00
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - name: Dump Database
        run: pnpm --filter=data run pull
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: SukkaLab/hv-monster-data
          personal_token: ${{ secrets.GIT_DEPLOY_TOKEN }}
          user_name: ${{ secrets.GIT_DEPLOY_USER }}
          user_email: ${{ secrets.GIT_DEPLOY_EMAIL }}
          publish_branch: master
          cname: hv-monsterdb-data.skk.moe
          publish_dir: ./packages/data/public
      - run: |
          mkdir -p /tmp/public/packages/api-server-on-vercel
          echo "Last updated at $(date -u)" > /tmp/public/last-run.txt
          cp ./packages/api-server-on-vercel/should-vercel-build.sh /tmp/public/packages/api-server-on-vercel/should-vercel-build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/public
          keep_files: true
          force_orphan: true
          publish_branch: dist
