name: Daily Update Full Database Dump

on:
  # Trigger update at UTC+0 23:00
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Dump Database
        run: pnpm --filter=data run pull
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: SukkaLab/hv-monster-data
          personal_token: ${{ secrets.GIT_DEPLOY_TOKEN }}
          user_name: ${{ secrets.GIT_DEPLOY_USER }}
          user_email: ${{ secrets.GIT_DEPLOY_EMAIL }}
          publish_branch: master
          cname: hv-monsterdb-data.skk.moe
          publish_dir: ./packages/data/public
